// https://api.weatherapi.com/v1/forecast.json?key=cf331fa56fde4a64b98185925232706&q=India&days=1&aqi=no&alerts=no
const weatherData = {
    "location": {
        "name": "New Delhi",
        "region": "Delhi",
        "country": "India",
        "lat": 28.6,
        "lon": 77.2,
        "tz_id": "Asia/Kolkata",
        "localtime_epoch": 1687892719,
        "localtime": "2023-06-28 0:35"
    },
    "current": {
        "last_updated_epoch": 1687892400,
        "last_updated": "2023-06-28 00:30",
        "temp_c": 28.0,
        "temp_f": 82.4,
        "is_day": 0,
        "condition": {
            "text": "Mist",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
            "code": 1030
        },
        "wind_mph": 3.8,
        "wind_kph": 6.1,
        "wind_degree": 50,
        "wind_dir": "NE",
        "pressure_mb": 1003.0,
        "pressure_in": 29.62,
        "precip_mm": 0.4,
        "precip_in": 0.02,
        "humidity": 100,
        "cloud": 50,
        "feelslike_c": 29.3,
        "feelslike_f": 84.7,
        "vis_km": 2.5,
        "vis_miles": 1.0,
        "uv": 1.0,
        "gust_mph": 8.1,
        "gust_kph": 13.0
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2023-06-28",
                "date_epoch": 1687910400,
                "day": {
                    "maxtemp_c": 39.3,
                    "maxtemp_f": 102.7,
                    "mintemp_c": 31.4,
                    "mintemp_f": 88.5,
                    "avgtemp_c": 35.5,
                    "avgtemp_f": 95.9,
                    "maxwind_mph": 11.2,
                    "maxwind_kph": 18.0,
                    "totalprecip_mm": 1.3,
                    "totalprecip_in": 0.05,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 9.9,
                    "avgvis_miles": 6.0,
                    "avghumidity": 43.0,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 85,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain possible",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063
                    },
                    "uv": 8.0
                },
                "astro": {
                    "sunrise": "05:26 AM",
                    "sunset": "07:23 PM",
                    "moonrise": "02:13 PM",
                    "moonset": "01:06 AM",
                    "moon_phase": "Waxing Gibbous",
                    "moon_illumination": "66",
                    "is_moon_up": 0,
                    "is_sun_up": 1
                },
                "hour": [
                    {
                        "time_epoch": 1687890600,
                        "time": "2023-06-28 00:00",
                        "temp_c": 33.6,
                        "temp_f": 92.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 7.6,
                        "wind_kph": 12.2,
                        "wind_degree": 82,
                        "wind_dir": "E",
                        "pressure_mb": 999.0,
                        "pressure_in": 29.5,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 51,
                        "cloud": 79,
                        "feelslike_c": 38.3,
                        "feelslike_f": 100.9,
                        "windchill_c": 33.6,
                        "windchill_f": 92.5,
                        "heatindex_c": 38.3,
                        "heatindex_f": 100.9,
                        "dewpoint_c": 22.0,
                        "dewpoint_f": 71.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 78,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 10.1,
                        "gust_kph": 16.2,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687894200,
                        "time": "2023-06-28 01:00",
                        "temp_c": 32.3,
                        "temp_f": 90.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 84,
                        "wind_dir": "E",
                        "pressure_mb": 1000.0,
                        "pressure_in": 29.52,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 56,
                        "cloud": 77,
                        "feelslike_c": 36.8,
                        "feelslike_f": 98.2,
                        "windchill_c": 32.3,
                        "windchill_f": 90.1,
                        "heatindex_c": 36.8,
                        "heatindex_f": 98.2,
                        "dewpoint_c": 22.3,
                        "dewpoint_f": 72.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 82,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 8.1,
                        "gust_kph": 13.0,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687897800,
                        "time": "2023-06-28 02:00",
                        "temp_c": 31.3,
                        "temp_f": 88.3,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            "code": 1240
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 71,
                        "wind_dir": "ENE",
                        "pressure_mb": 999.0,
                        "pressure_in": 29.51,
                        "precip_mm": 1.5,
                        "precip_in": 0.06,
                        "humidity": 60,
                        "cloud": 72,
                        "feelslike_c": 35.8,
                        "feelslike_f": 96.4,
                        "windchill_c": 31.3,
                        "windchill_f": 88.3,
                        "heatindex_c": 35.8,
                        "heatindex_f": 96.4,
                        "dewpoint_c": 22.7,
                        "dewpoint_f": 72.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 85,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.3,
                        "gust_kph": 10.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687901400,
                        "time": "2023-06-28 03:00",
                        "temp_c": 32.2,
                        "temp_f": 90.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 6.0,
                        "wind_kph": 9.7,
                        "wind_degree": 62,
                        "wind_dir": "ENE",
                        "pressure_mb": 999.0,
                        "pressure_in": 29.51,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 56,
                        "cloud": 82,
                        "feelslike_c": 36.6,
                        "feelslike_f": 97.9,
                        "windchill_c": 32.2,
                        "windchill_f": 90.0,
                        "heatindex_c": 36.6,
                        "heatindex_f": 97.9,
                        "dewpoint_c": 22.2,
                        "dewpoint_f": 72.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 88,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 8.3,
                        "gust_kph": 13.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687905000,
                        "time": "2023-06-28 04:00",
                        "temp_c": 32.6,
                        "temp_f": 90.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 7.8,
                        "wind_kph": 12.6,
                        "wind_degree": 77,
                        "wind_dir": "ENE",
                        "pressure_mb": 999.0,
                        "pressure_in": 29.5,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 54,
                        "cloud": 87,
                        "feelslike_c": 36.9,
                        "feelslike_f": 98.4,
                        "windchill_c": 32.6,
                        "windchill_f": 90.7,
                        "heatindex_c": 36.9,
                        "heatindex_f": 98.4,
                        "dewpoint_c": 21.9,
                        "dewpoint_f": 71.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 88,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 10.5,
                        "gust_kph": 16.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687908600,
                        "time": "2023-06-28 05:00",
                        "temp_c": 31.9,
                        "temp_f": 89.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 10.3,
                        "wind_kph": 16.6,
                        "wind_degree": 88,
                        "wind_dir": "E",
                        "pressure_mb": 1000.0,
                        "pressure_in": 29.52,
                        "precip_mm": 1.9,
                        "precip_in": 0.07,
                        "humidity": 56,
                        "cloud": 83,
                        "feelslike_c": 36.1,
                        "feelslike_f": 97.0,
                        "windchill_c": 31.9,
                        "windchill_f": 89.4,
                        "heatindex_c": 36.1,
                        "heatindex_f": 97.0,
                        "dewpoint_c": 22.1,
                        "dewpoint_f": 71.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 83,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 13.9,
                        "gust_kph": 22.3,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687912200,
                        "time": "2023-06-28 06:00",
                        "temp_c": 31.5,
                        "temp_f": 88.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 10.3,
                        "wind_kph": 16.6,
                        "wind_degree": 101,
                        "wind_dir": "ESE",
                        "pressure_mb": 1000.0,
                        "pressure_in": 29.54,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 57,
                        "cloud": 82,
                        "feelslike_c": 35.5,
                        "feelslike_f": 95.9,
                        "windchill_c": 31.5,
                        "windchill_f": 88.7,
                        "heatindex_c": 35.5,
                        "heatindex_f": 95.9,
                        "dewpoint_c": 22.0,
                        "dewpoint_f": 71.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 81,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 13.2,
                        "gust_kph": 21.2,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687915800,
                        "time": "2023-06-28 07:00",
                        "temp_c": 32.3,
                        "temp_f": 90.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 11.9,
                        "wind_kph": 19.1,
                        "wind_degree": 104,
                        "wind_dir": "ESE",
                        "pressure_mb": 1001.0,
                        "pressure_in": 29.57,
                        "precip_mm": 0.3,
                        "precip_in": 0.01,
                        "humidity": 55,
                        "cloud": 86,
                        "feelslike_c": 36.6,
                        "feelslike_f": 97.9,
                        "windchill_c": 32.3,
                        "windchill_f": 90.1,
                        "heatindex_c": 36.6,
                        "heatindex_f": 97.9,
                        "dewpoint_c": 22.1,
                        "dewpoint_f": 71.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 66,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 14.5,
                        "gust_kph": 23.4,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687919400,
                        "time": "2023-06-28 08:00",
                        "temp_c": 33.5,
                        "temp_f": 92.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 11.9,
                        "wind_kph": 19.1,
                        "wind_degree": 112,
                        "wind_dir": "ESE",
                        "pressure_mb": 1002.0,
                        "pressure_in": 29.59,
                        "precip_mm": 0.5,
                        "precip_in": 0.02,
                        "humidity": 52,
                        "cloud": 89,
                        "feelslike_c": 38.4,
                        "feelslike_f": 101.1,
                        "windchill_c": 33.5,
                        "windchill_f": 92.3,
                        "heatindex_c": 38.4,
                        "heatindex_f": 101.1,
                        "dewpoint_c": 22.3,
                        "dewpoint_f": 72.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 68,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 14.5,
                        "gust_kph": 23.4,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687923000,
                        "time": "2023-06-28 09:00",
                        "temp_c": 34.8,
                        "temp_f": 94.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 10.3,
                        "wind_kph": 16.6,
                        "wind_degree": 120,
                        "wind_dir": "ESE",
                        "pressure_mb": 1002.0,
                        "pressure_in": 29.59,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 47,
                        "cloud": 70,
                        "feelslike_c": 39.9,
                        "feelslike_f": 103.8,
                        "windchill_c": 34.8,
                        "windchill_f": 94.6,
                        "heatindex_c": 39.9,
                        "heatindex_f": 103.8,
                        "dewpoint_c": 21.9,
                        "dewpoint_f": 71.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 73,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.5,
                        "gust_kph": 20.2,
                        "uv": 7.0
                    },
                    {
                        "time_epoch": 1687926600,
                        "time": "2023-06-28 10:00",
                        "temp_c": 36.2,
                        "temp_f": 97.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 10.3,
                        "wind_kph": 16.6,
                        "wind_degree": 126,
                        "wind_dir": "SE",
                        "pressure_mb": 1002.0,
                        "pressure_in": 29.58,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 43,
                        "cloud": 79,
                        "feelslike_c": 41.4,
                        "feelslike_f": 106.5,
                        "windchill_c": 36.2,
                        "windchill_f": 97.2,
                        "heatindex_c": 41.4,
                        "heatindex_f": 106.5,
                        "dewpoint_c": 21.6,
                        "dewpoint_f": 70.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 65,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.5,
                        "gust_kph": 20.2,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1687930200,
                        "time": "2023-06-28 11:00",
                        "temp_c": 38.2,
                        "temp_f": 100.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 131,
                        "wind_dir": "SE",
                        "pressure_mb": 1001.0,
                        "pressure_in": 29.57,
                        "precip_mm": 0.5,
                        "precip_in": 0.02,
                        "humidity": 40,
                        "cloud": 84,
                        "feelslike_c": 44.4,
                        "feelslike_f": 111.9,
                        "windchill_c": 38.2,
                        "windchill_f": 100.8,
                        "heatindex_c": 44.4,
                        "heatindex_f": 111.9,
                        "dewpoint_c": 22.0,
                        "dewpoint_f": 71.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 68,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1687933800,
                        "time": "2023-06-28 12:00",
                        "temp_c": 38.3,
                        "temp_f": 100.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 127,
                        "wind_dir": "SE",
                        "pressure_mb": 1001.0,
                        "pressure_in": 29.55,
                        "precip_mm": 0.5,
                        "precip_in": 0.02,
                        "humidity": 39,
                        "cloud": 78,
                        "feelslike_c": 44.2,
                        "feelslike_f": 111.6,
                        "windchill_c": 38.3,
                        "windchill_f": 100.9,
                        "heatindex_c": 44.2,
                        "heatindex_f": 111.6,
                        "dewpoint_c": 21.7,
                        "dewpoint_f": 71.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 85,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1687937400,
                        "time": "2023-06-28 13:00",
                        "temp_c": 38.7,
                        "temp_f": 101.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 8.3,
                        "wind_kph": 13.3,
                        "wind_degree": 128,
                        "wind_dir": "SE",
                        "pressure_mb": 1000.0,
                        "pressure_in": 29.53,
                        "precip_mm": 0.4,
                        "precip_in": 0.02,
                        "humidity": 39,
                        "cloud": 71,
                        "feelslike_c": 45.2,
                        "feelslike_f": 113.4,
                        "windchill_c": 38.7,
                        "windchill_f": 101.7,
                        "heatindex_c": 45.2,
                        "heatindex_f": 113.4,
                        "dewpoint_c": 22.2,
                        "dewpoint_f": 72.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 89,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 10.5,
                        "gust_kph": 16.9,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1687941000,
                        "time": "2023-06-28 14:00",
                        "temp_c": 39.3,
                        "temp_f": 102.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 124,
                        "wind_dir": "SE",
                        "pressure_mb": 999.0,
                        "pressure_in": 29.51,
                        "precip_mm": 0.8,
                        "precip_in": 0.03,
                        "humidity": 37,
                        "cloud": 72,
                        "feelslike_c": 45.5,
                        "feelslike_f": 113.9,
                        "windchill_c": 39.3,
                        "windchill_f": 102.7,
                        "heatindex_c": 45.5,
                        "heatindex_f": 113.9,
                        "dewpoint_c": 21.7,
                        "dewpoint_f": 71.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 78,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 8.1,
                        "gust_kph": 13.0,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1687944600,
                        "time": "2023-06-28 15:00",
                        "temp_c": 39.4,
                        "temp_f": 102.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 123,
                        "wind_dir": "ESE",
                        "pressure_mb": 999.0,
                        "pressure_in": 29.49,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 35,
                        "cloud": 75,
                        "feelslike_c": 44.9,
                        "feelslike_f": 112.8,
                        "windchill_c": 39.4,
                        "windchill_f": 102.9,
                        "heatindex_c": 44.9,
                        "heatindex_f": 112.8,
                        "dewpoint_c": 21.0,
                        "dewpoint_f": 69.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 63,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 6.0,
                        "gust_kph": 9.7,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1687948200,
                        "time": "2023-06-28 16:00",
                        "temp_c": 38.8,
                        "temp_f": 101.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 124,
                        "wind_dir": "SE",
                        "pressure_mb": 998.0,
                        "pressure_in": 29.47,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 35,
                        "cloud": 75,
                        "feelslike_c": 43.7,
                        "feelslike_f": 110.7,
                        "windchill_c": 38.8,
                        "windchill_f": 101.8,
                        "heatindex_c": 43.7,
                        "heatindex_f": 110.7,
                        "dewpoint_c": 20.6,
                        "dewpoint_f": 69.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 89,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 7.6,
                        "gust_kph": 12.2,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1687951800,
                        "time": "2023-06-28 17:00",
                        "temp_c": 38.4,
                        "temp_f": 101.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 6.7,
                        "wind_kph": 10.8,
                        "wind_degree": 119,
                        "wind_dir": "ESE",
                        "pressure_mb": 998.0,
                        "pressure_in": 29.46,
                        "precip_mm": 1.1,
                        "precip_in": 0.04,
                        "humidity": 36,
                        "cloud": 82,
                        "feelslike_c": 43.2,
                        "feelslike_f": 109.8,
                        "windchill_c": 38.4,
                        "windchill_f": 101.1,
                        "heatindex_c": 43.2,
                        "heatindex_f": 109.8,
                        "dewpoint_c": 20.6,
                        "dewpoint_f": 69.1,
                        "will_it_rain": 1,
                        "chance_of_rain": 80,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 8.9,
                        "gust_kph": 14.4,
                        "uv": 8.0
                    },
                    {
                        "time_epoch": 1687955400,
                        "time": "2023-06-28 18:00",
                        "temp_c": 37.8,
                        "temp_f": 100.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 113,
                        "wind_dir": "ESE",
                        "pressure_mb": 998.0,
                        "pressure_in": 29.47,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 37,
                        "cloud": 45,
                        "feelslike_c": 42.3,
                        "feelslike_f": 108.1,
                        "windchill_c": 37.8,
                        "windchill_f": 100.0,
                        "heatindex_c": 42.3,
                        "heatindex_f": 108.1,
                        "dewpoint_c": 20.4,
                        "dewpoint_f": 68.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.2,
                        "gust_kph": 11.5,
                        "uv": 9.0
                    },
                    {
                        "time_epoch": 1687959000,
                        "time": "2023-06-28 19:00",
                        "temp_c": 37.0,
                        "temp_f": 98.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 6.5,
                        "wind_kph": 10.4,
                        "wind_degree": 109,
                        "wind_dir": "ESE",
                        "pressure_mb": 998.0,
                        "pressure_in": 29.48,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 38,
                        "cloud": 49,
                        "feelslike_c": 41.4,
                        "feelslike_f": 106.5,
                        "windchill_c": 37.0,
                        "windchill_f": 98.6,
                        "heatindex_c": 41.4,
                        "heatindex_f": 106.5,
                        "dewpoint_c": 20.4,
                        "dewpoint_f": 68.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.3,
                        "gust_kph": 13.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687962600,
                        "time": "2023-06-28 20:00",
                        "temp_c": 36.2,
                        "temp_f": 97.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            "code": 1240
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 131,
                        "wind_dir": "SE",
                        "pressure_mb": 1000.0,
                        "pressure_in": 29.52,
                        "precip_mm": 0.3,
                        "precip_in": 0.01,
                        "humidity": 40,
                        "cloud": 55,
                        "feelslike_c": 40.3,
                        "feelslike_f": 104.5,
                        "windchill_c": 36.2,
                        "windchill_f": 97.2,
                        "heatindex_c": 40.3,
                        "heatindex_f": 104.5,
                        "dewpoint_c": 20.4,
                        "dewpoint_f": 68.7,
                        "will_it_rain": 1,
                        "chance_of_rain": 79,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.7,
                        "gust_kph": 17.3,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687966200,
                        "time": "2023-06-28 21:00",
                        "temp_c": 35.8,
                        "temp_f": 96.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            "code": 1003
                        },
                        "wind_mph": 7.4,
                        "wind_kph": 11.9,
                        "wind_degree": 131,
                        "wind_dir": "SE",
                        "pressure_mb": 1000.0,
                        "pressure_in": 29.53,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "humidity": 41,
                        "cloud": 48,
                        "feelslike_c": 39.9,
                        "feelslike_f": 103.8,
                        "windchill_c": 35.8,
                        "windchill_f": 96.4,
                        "heatindex_c": 39.9,
                        "heatindex_f": 103.8,
                        "dewpoint_c": 20.6,
                        "dewpoint_f": 69.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.4,
                        "gust_kph": 15.1,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687969800,
                        "time": "2023-06-28 22:00",
                        "temp_c": 35.8,
                        "temp_f": 96.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 8.3,
                        "wind_kph": 13.3,
                        "wind_degree": 130,
                        "wind_dir": "SE",
                        "pressure_mb": 1000.0,
                        "pressure_in": 29.54,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "humidity": 41,
                        "cloud": 73,
                        "feelslike_c": 39.9,
                        "feelslike_f": 103.8,
                        "windchill_c": 35.8,
                        "windchill_f": 96.4,
                        "heatindex_c": 39.9,
                        "heatindex_f": 103.8,
                        "dewpoint_c": 20.5,
                        "dewpoint_f": 68.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 65,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.5,
                        "gust_kph": 16.9,
                        "uv": 1.0
                    },
                    {
                        "time_epoch": 1687973400,
                        "time": "2023-06-28 23:00",
                        "temp_c": 35.4,
                        "temp_f": 95.7,
                        "is_day": 0,
                        "condition": {
                            "text": "Light rain shower",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                            "code": 1240
                        },
                        "wind_mph": 8.5,
                        "wind_kph": 13.7,
                        "wind_degree": 138,
                        "wind_dir": "SE",
                        "pressure_mb": 1000.0,
                        "pressure_in": 29.53,
                        "precip_mm": 0.2,
                        "precip_in": 0.01,
                        "humidity": 42,
                        "cloud": 61,
                        "feelslike_c": 39.5,
                        "feelslike_f": 103.1,
                        "windchill_c": 35.4,
                        "windchill_f": 95.7,
                        "heatindex_c": 39.5,
                        "heatindex_f": 103.1,
                        "dewpoint_c": 20.6,
                        "dewpoint_f": 69.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 63,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.7,
                        "gust_kph": 17.3,
                        "uv": 1.0
                    }
                ]
            }
        ]
    }
}

// const weatherData =
//     fetch(
//         'https://api.weatherapi.com/v1/forecast.json?key=cf331fa56fde4a64b98185925232706&q=India&days=1&aqi=no&alerts=no').then(response => response.json())
//     console.log(weatherData)
export default weatherData;